### ISSUE TITLE
Emit Telemetry events

### ISSUE THREAD

**Issue by stephanos** [ananthakumaran/memcachex#22]
Hello!

[Telemetry](https://github.com/beam-telemetry/telemetry) is getting traction now that it's included in [Phoenix](https://github.com/phoenixframework/phoenix/commit/4d61eacd83d61899a895167715d8754c5c8187be) and [Ecto](https://github.com/elixir-ecto/ecto/commit/ee8a9ea002f8809825d3bd5a3bc34aa863f223ee) out-of-the-box. What's your stance on emitting telemetry events from this library? Would you welcome contributions?

It would allow users of this library to capture important metrics and send them to their monitoring solution. This way, we save everyone the time to instrument their own usage of this library.

Stephan

**Comment by ananthakumaran** [comment]
I am definitely interested in adding support for telemetry. I would be happy to accept contributions. It would be great if you could put together a spec that explains what events (including metadata, measurements) would be published, sort of like [this](https://hexdocs.pm/redix/Redix.Telemetry.html)

**Comment by stephanos** [comment]
Cool! Their documentation is really neat; I'll get a first draft out as soon as I can :)

**Comment by stephanos** [comment]
`[:memcachex, :commands]`
  - `:elapsed_time` (integer) the elapsed time that it took to send the pipeline to the server and get a reply. (a measurement)
  - `:server` the server the commands were sent to
  - `:opts` the options that were sent along with the command
  - `:server_options` the server options that were sent along with the command
  - `:commands` the commands sent to the server
  - `:start_time` the system time when the commands were issued

`[:memcachex, :commands, :error]`
  - `:server` the server the commands were sent to
  - `:opts` the options that were sent along with the command
  - `:server_options` the server options that were sent along with the command
  - `:commands` the commands sent to the server
  - `:start_time` the system time when the commands were issued
  - `:reason` the error reason.

`[:memcachex, :connection]`
  - `:reconnected` boolean to indicate this was a reconnection
  - `:opts` the connection options

`[:memcachex, :connection, :error]`
  - `:opts` the connection options
  - `:reason` the error reason.


Some notes:
  - I'm not intimately familiar with the codebase
  - I followed the Redix patterns, they seem to make sense
  - I'm not sure the connection should include the entire `opts` or just the host/port for privacy/security reasons
  - not sure I'd have a separate event for reconnection like Redix, seems overkill
  - I assumed that even with a single command, it'd be wrapped in a list (ie commands)

Let me know what you think!
