### ISSUE TITLE
Support for mget and mset?

### ISSUE THREAD

**Issue by cjbottaro** [ananthakumaran/memcachex#4]
Can you add support for these two operations?

I'm currently writing a higher level memcached client (support for clusters, fetch, mfetch, Ecto integration) that uses your client under the hood and I need mget and mset in order for mfetch to be efficient.

Thank you.

**Comment by cjbottaro** [comment]
Ahh, I can get what I want with the low level API:

```elixir
Memcache.Connection.execute_quiet(pid, [{:GETKQ, ["3"]}, {:GETKQ, ["1"]}, {:GETKQ, ["foo"]}])
```

Still would be nice to have it in the high level API.

**Comment by ananthakumaran** [comment]
Yes, the high level api for execute_quiet is not provided yet. The api is not quite straight forward. Should mget return a hash? how should it handle errors? should it ignore errors for single key.

I will start to work on it when I get the time.
