### ISSUE TITLE
Cluster?

### ISSUE THREAD

**Issue by cjbottaro** [ananthakumaran/memcachex#5]
Hi.  The hexdocs for the project show a module `Memcache.Cluster` and `Memcache.Cluster.Hash`, but I can't find them in the source code.

Does this client support memcached clusters with the same consistent hashing algorithm as the Ruby clients (Dalli, Memcache)?

Thanks for the info!

**Comment by ananthakumaran** [comment]
No, It doesn't support cluster. I experimented with cluster, but abandoned it later because https://github.com/twitter/twemproxy seems to solve the problem nicely across different clients written in different language. I have fixed the docs.

**Comment by cjbottaro** [comment]
Ha, this is kind of funny... I implemented cluster support a few months ago and completely forgot about it.  I'm going to clean up the code, flesh out the supervision trees, document it, then publish it.  It's a separate application, but it uses `memcachex` under the hood.

twemproxy looks cool, but we hit IO limits before cpu limits in our memcached cluster, so doing the clustering in the client is beneficial for us.  Hmm, I guess one could have multiple twemproxy machines though.

**Comment by cjbottaro** [comment]
Here it is:  https://github.com/cjbottaro/cream_ex
